version: '3.8'

services:
  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - '6378:6379'
    command: redis-server --save 20 1 --loglevel warning
